export const CATEGORY_HIERARCHY = {
  handyman: {
    id: 'handyman',
    name: 'Handyman',
    animation: '/animations/handyman.json',
    description: 'Home repair and maintenance services',
    subcategories: [
      { id: 'electrician', name: 'Electrician' },
      { id: 'plumber', name: 'Plumber' },
      { id: 'carpenter', name: 'Carpenter' },
      { id: 'painter', name: 'Painter' },
      { id: 'tiler', name: 'Tiler' },
      { id: 'roofer', name: 'Roofer' },
      { id: 'locksmith', name: 'Locksmith' },
      { id: 'appliance-repair', name: 'Appliance Repair' },
      { id: 'general-handyman', name: 'General Handyman' },
      { id: 'hvac', name: 'HVAC Services' },
      { id: 'flooring', name: 'Flooring' },
      { id: 'drywall', name: 'Drywall Repair' },
      { id: 'fence', name: 'Fence Installation' },
      { id: 'deck', name: 'Deck Building' },
      { id: 'cabinets', name: 'Cabinet Installation' },
      { id: 'bathroom', name: 'Bathroom Renovation' },
      { id: 'kitchen', name: 'Kitchen Installation' },
    ],
  },
  education: {
    id: 'education',
    name: 'Education',
    animation: '/animations/education.json',
    description: 'Tutoring and educational services',
    subcategories: [
      {
        id: 'tutors',
        name: 'Tutors',
        subcategories: [
          {
            id: 'mathematics',
            name: 'Mathematics',
            grades: ['Grade 1-3', 'Grade 4-6', 'Grade 7-9', 'Grade 10-12', 'University'],
          },
          {
            id: 'science',
            name: 'Science',
            grades: ['Grade 1-3', 'Grade 4-6', 'Grade 7-9', 'Grade 10-12', 'University'],
          },
          {
            id: 'english',
            name: 'English',
            grades: ['Grade 1-3', 'Grade 4-6', 'Grade 7-9', 'Grade 10-12', 'University'],
          },
          {
            id: 'afrikaans',
            name: 'Afrikaans',
            grades: ['Grade 1-3', 'Grade 4-6', 'Grade 7-9', 'Grade 10-12', 'University'],
          },
          {
            id: 'history',
            name: 'History',
            grades: ['Grade 4-6', 'Grade 7-9', 'Grade 10-12', 'University'],
          },
          {
            id: 'geography',
            name: 'Geography',
            grades: ['Grade 4-6', 'Grade 7-9', 'Grade 10-12', 'University'],
          },
          {
            id: 'accounting',
            name: 'Accounting',
            grades: ['Grade 10-12', 'University'],
          },
          {
            id: 'business-studies',
            name: 'Business Studies',
            grades: ['Grade 10-12', 'University'],
          },
          {
            id: 'physics',
            name: 'Physics',
            grades: ['Grade 10-12', 'University'],
          },
          {
            id: 'chemistry',
            name: 'Chemistry',
            grades: ['Grade 10-12', 'University'],
          },
          {
            id: 'biology',
            name: 'Biology',
            grades: ['Grade 10-12', 'University'],
          },
          {
            id: 'computer-science',
            name: 'Computer Science',
            grades: ['Grade 7-9', 'Grade 10-12', 'University'],
          },
          {
            id: 'coding',
            name: 'Coding',
            grades: ['Grade 4-6', 'Grade 7-9', 'Grade 10-12', 'University', 'Adult'],
          },
          {
            id: 'music',
            name: 'Music',
            grades: ['Beginner', 'Intermediate', 'Advanced', 'Professional'],
          },
          {
            id: 'art',
            name: 'Art',
            grades: ['Beginner', 'Intermediate', 'Advanced', 'Professional'],
          },
          {
            id: 'languages',
            name: 'Languages',
            grades: ['Beginner', 'Intermediate', 'Advanced', 'Professional'],
          },
        ],
      },
      { id: 'test-prep', name: 'Test Prep' },
      { id: 'language-learning', name: 'Language Learning' },
      { id: 'online-courses', name: 'Online Courses' },
      { id: 'study-skills', name: 'Study Skills' },
      { id: 'college-applications', name: 'College Applications' },
      { id: 'adult-education', name: 'Adult Education' },
    ],
  },
  cleaning: {
    id: 'cleaning',
    name: 'Cleaning',
    animation: '/animations/cleaning.json',
    description: 'Professional cleaning services',
    subcategories: [
      { id: 'house-cleaning', name: 'House Cleaning' },
      { id: 'deep-cleaning', name: 'Deep Cleaning' },
      { id: 'office-cleaning', name: 'Office Cleaning' },
      { id: 'window-cleaning', name: 'Window Cleaning' },
      { id: 'carpet-cleaning', name: 'Carpet Cleaning' },
      { id: 'move-in-out', name: 'Move In/Out' },
      { id: 'post-construction', name: 'Post-Construction Cleaning' },
      { id: 'medical-facility', name: 'Medical Facility Cleaning' },
      { id: 'industrial-cleaning', name: 'Industrial Cleaning' },
      { id: 'post-event', name: 'Post-Event Cleaning' },
      { id: 'upholstery', name: 'Upholstery Cleaning' },
      { id: 'oven-cleaning', name: 'Oven Cleaning' },
    ],
  },
  petcare: {
    id: 'petcare',
    name: 'Pet Care',
    animation: '/animations/petcare.json',
    description: 'Pet services and care',
    subcategories: [
      { id: 'dog-walking', name: 'Dog Walking' },
      { id: 'pet-sitting', name: 'Pet Sitting' },
      { id: 'pet-grooming', name: 'Pet Grooming' },
      { id: 'pet-training', name: 'Pet Training' },
      { id: 'pet-feeding', name: 'Pet Feeding' },
      { id: 'pet-boarding', name: 'Pet Boarding' },
      { id: 'pet-transportation', name: 'Pet Transportation' },
      { id: 'pet-photography', name: 'Pet Photography' },
      { id: 'pet-daycare', name: 'Pet Daycare' },
      { id: 'pet-behavior', name: 'Pet Behavior Consultation' },
      { id: 'exotic-pet', name: 'Exotic Pet Care' },
    ],
  },
  fitness: {
    id: 'fitness',
    name: 'Fitness',
    animation: '/animations/fitness.json',
    description: 'Personal training and wellness',
    subcategories: [
      { id: 'personal-trainers', name: 'Personal Trainers' },
      {
        id: 'sport-coaching',
        name: 'Sport-Specific Coaching',
        subcategories: [
          { id: 'cycling', name: 'Cycling' },
          { id: 'swimming', name: 'Swimming' },
          { id: 'running', name: 'Running' },
          { id: 'tennis', name: 'Tennis' },
          { id: 'soccer', name: 'Soccer' },
          { id: 'basketball', name: 'Basketball' },
          { id: 'golf', name: 'Golf' },
          { id: 'martial-arts', name: 'Martial Arts' },
          { id: 'yoga', name: 'Yoga' },
          { id: 'pilates', name: 'Pilates' },
        ],
      },
      { id: 'wellness', name: 'Wellness' },
      { id: 'nutritionist', name: 'Nutritionist' },
      { id: 'massage-therapist', name: 'Massage Therapist' },
      { id: 'meditation', name: 'Meditation' },
      { id: 'crossfit', name: 'CrossFit' },
      { id: 'weightlifting', name: 'Weightlifting Coaching' },
      { id: 'group-fitness', name: 'Group Fitness' },
      { id: 'rehabilitation', name: 'Rehabilitation Training' },
      { id: 'senior-fitness', name: 'Senior Fitness' },
      { id: 'kids-fitness', name: 'Kids Fitness' },
    ],
  },
  automotive: {
    id: 'automotive',
    name: 'Automotive',
    animation: '/animations/automotive.json',
    description: 'Vehicle repair and maintenance',
    subcategories: [
      { id: 'mobile-mechanic', name: 'Mobile Mechanic' },
      { id: 'car-detailing', name: 'Car Detailing' },
      { id: 'tire-service', name: 'Tire Service' },
      { id: 'battery-service', name: 'Battery Service' },
      { id: 'car-wash', name: 'Car Wash' },
      { id: 'auto-body', name: 'Auto Body Repair' },
      { id: 'engine-repair', name: 'Engine Repair' },
      { id: 'transmission', name: 'Transmission Service' },
      { id: 'ac-repair', name: 'AC Repair' },
      { id: 'diagnostic', name: 'Diagnostic Services' },
      { id: 'pre-purchase', name: 'Pre-Purchase Inspection' },
      { id: 'roadside', name: 'Roadside Assistance' },
    ],
  },
  gardening: {
    id: 'gardening',
    name: 'Gardening & Landscaping',
    animation: '/animations/gardening.json',
    description: 'Garden and landscape services',
    subcategories: [
      { id: 'gardening', name: 'Gardening' },
      { id: 'landscaping', name: 'Landscaping' },
      { id: 'lawn-mowing', name: 'Lawn Mowing' },
      { id: 'tree-trimming', name: 'Tree Trimming' },
      { id: 'irrigation', name: 'Irrigation' },
      { id: 'pest-control', name: 'Pest Control' },
      { id: 'garden-design', name: 'Garden Design' },
      { id: 'plant-care', name: 'Plant Care' },
      { id: 'seasonal-planting', name: 'Seasonal Planting' },
      { id: 'composting', name: 'Composting' },
      { id: 'garden-maintenance', name: 'Garden Maintenance Plans' },
      { id: 'irrigation-installation', name: 'Irrigation Installation' },
    ],
  },
  personalservices: {
    id: 'personalservices',
    name: 'Personal Services',
    animation: '/animations/personalservices.json',
    description: 'Personal assistance and care',
    subcategories: [
      { id: 'errands', name: 'Errands' },
      { id: 'shopping', name: 'Shopping' },
      { id: 'house-sitting', name: 'House Sitting' },
      { id: 'babysitting', name: 'Babysitting' },
      { id: 'elderly-care', name: 'Elderly Care' },
      { id: 'event-planning', name: 'Event Planning' },
      { id: 'personal-assistant', name: 'Personal Assistant' },
      { id: 'concierge', name: 'Concierge Services' },
      { id: 'meal-prep', name: 'Meal Prep' },
      { id: 'personal-shopping', name: 'Personal Shopping' },
      { id: 'travel-planning', name: 'Travel Planning' },
      { id: 'gift-wrapping', name: 'Gift Wrapping' },
    ],
  },
  computer: {
    id: 'computer',
    name: 'Technology & IT',
    animation: '/animations/computer.json',
    description: 'IT and technology services',
    subcategories: [
      { id: 'it-support', name: 'IT Support' },
      { id: 'web-development', name: 'Web Development' },
      { id: 'app-development', name: 'App Development' },
      { id: 'graphic-design', name: 'Graphic Design' },
      { id: 'cybersecurity', name: 'Cybersecurity' },
      { id: 'cloud-services', name: 'Cloud Services' },
      { id: 'database', name: 'Database Management' },
      { id: 'network-setup', name: 'Network Setup' },
      { id: 'tech-consulting', name: 'Tech Consulting' },
      { id: 'software-testing', name: 'Software Testing' },
      { id: 'ui-ux', name: 'UI/UX Design' },
    ],
  },
  professionalservices: {
    id: 'professionalservices',
    name: 'Professional Services',
    animation: '/animations/professionalservices.json',
    description: 'Business and professional services',
    subcategories: [
      { id: 'accounting', name: 'Accounting' },
      { id: 'legal', name: 'Legal Services' },
      { id: 'consulting', name: 'Consulting' },
      { id: 'marketing', name: 'Marketing' },
      { id: 'writing', name: 'Writing & Content' },
      { id: 'translation', name: 'Translation' },
      { id: 'business-plan', name: 'Business Plan Writing' },
      { id: 'financial-planning', name: 'Financial Planning' },
      { id: 'hr-consulting', name: 'HR Consulting' },
      { id: 'project-management', name: 'Project Management' },
      { id: 'brand-strategy', name: 'Brand Strategy' },
      { id: 'public-relations', name: 'Public Relations' },
    ],
  },
  influencer: {
    id: 'influencer',
    name: 'Influencing',
    animation: '/animations/influencer.json',
    description: 'Social media and influencer services',
    subcategories: [
      { id: 'social-media-management', name: 'Social Media Management' },
      { id: 'content-creation', name: 'Content Creation' },
      { id: 'brand-partnerships', name: 'Brand Partnerships' },
      { id: 'influencer-marketing', name: 'Influencer Marketing' },
      { id: 'personal-branding', name: 'Personal Branding' },
      { id: 'social-strategy', name: 'Social Media Strategy' },
      { id: 'influencer-outreach', name: 'Influencer Outreach' },
      { id: 'content-strategy', name: 'Content Strategy' },
    ],
  },
  photography: {
    id: 'photography',
    name: 'Photography',
    animation: '/animations/photography.json',
    description: 'Professional photography services',
    subcategories: [
      { id: 'portrait', name: 'Portrait' },
      { id: 'event', name: 'Event' },
      { id: 'product', name: 'Product' },
      { id: 'wedding', name: 'Wedding' },
      { id: 'real-estate', name: 'Real Estate' },
      { id: 'fashion', name: 'Fashion' },
      { id: 'food', name: 'Food' },
      { id: 'landscape', name: 'Landscape' },
      { id: 'aerial', name: 'Aerial' },
      { id: 'sports', name: 'Sports' },
      { id: 'pet', name: 'Pet' },
      { id: 'corporate', name: 'Corporate Photography' },
    ],
  },
  videography: {
    id: 'videography',
    name: 'Videography',
    animation: '/animations/videography.json',
    description: 'Professional videography services',
    subcategories: [
      { id: 'wedding', name: 'Wedding' },
      { id: 'corporate', name: 'Corporate' },
      { id: 'event', name: 'Event' },
      { id: 'music-video', name: 'Music Video Production' },
      { id: 'documentary', name: 'Documentary Filming' },
      { id: 'real-estate', name: 'Real Estate Videography' },
      { id: 'drone', name: 'Drone Videography' },
      { id: 'video-editing', name: 'Video Editing' },
      { id: 'commercial', name: 'Commercial Videography' },
      { id: 'promotional', name: 'Promotional Videos' },
      { id: 'live-streaming', name: 'Live Streaming' },
    ],
  },
  music: {
    id: 'music',
    name: 'Music',
    animation: '/animations/music.json',
    description: 'Music and audio services',
    subcategories: [
      { id: 'music-production', name: 'Music Production' },
      { id: 'music-lessons', name: 'Music Lessons' },
      { id: 'dj-services', name: 'DJ Services' },
      { id: 'live-performance', name: 'Live Performance' },
      { id: 'music-composition', name: 'Music Composition' },
      { id: 'audio-engineering', name: 'Audio Engineering' },
      { id: 'music-mixing', name: 'Music Mixing' },
      { id: 'songwriting', name: 'Songwriting' },
      { id: 'sound-design', name: 'Sound Design' },
      { id: 'podcast-production', name: 'Podcast Production' },
      { id: 'music-therapy', name: 'Music Therapy' },
      { id: 'instrument-repair', name: 'Instrument Repair' },
    ],
  },
}

// Flatten for simple grid display
export const FLAT_CATEGORIES = Object.values(CATEGORY_HIERARCHY).map((cat) => ({
  id: cat.id,
  name: cat.name,
  animation: cat.animation,
  description: cat.description,
  subcategoryCount: cat.subcategories?.length || 0,
}))

